version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven dependencies...
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Building the JAR file...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully on `date`

artifacts:
  files:
    - target/*.jar
